routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

//start new root
//home page
Route::get('/','GumiHomeController@index')->name('gumi_home.index');
Route::get('/gumi-home','GumiHomeController@index')->name('gumi_home.index');
Route::get('/gumi-destinations','GumiHomeController@destinations')->name('gumi_destination.destinations');
Route::get('/gumi-blogs','GumiHomeController@blogs')->name('gumi_blog.blogs');
Route::get('/gumi-events','GumiHomeController@events')->name('gumi_event.events');
Route::get('/gumi-destination-detail/{seo_link}','GumiHomeController@destination_detail')->name('gumi_destination.detail');
Route::get('/gumi-blog-detail/{seo_link}','GumiHomeController@blog_detail')->name('gumi_blog.detail');
Route::get('/gumi-event-detail/{seo_link}','GumiHomeController@event_detail')->name('gumi_event.detail');
//end migrasi route

Route::get('/tentang-gumi-lombok', function () {
    return view('welcome');
})->name('gumi');




Route::get('/old_home', 'DepanController@index')->name('depan.index');
// Route::put('/detail-blog/{blog_id}','DepanController@detailBlog');
Route::get('/detail-blog/{blog_id}', 'DepanController@detailBlog')->name('depan.blog_detail');
Route::get('/detail-destinasi/{destination_id}','DepanController@detailDestinasi')->name('depan.destinasi_detail');
Route::get('/informasi-category/{blog_category}','DepanController@category')->name('depan.blog_category');
Route::get('/informasi-destinasi-wisata','DepanController@allDestinasi')->name('depan.semu_destinasi');

Route::get('/maps','DepanController@maps')->name('depan.maps');


// Route::resource('/order', 'OrderController');

Route::get('wisata','WisataController@index')->middleware('api');
Route::post('wisata','WisataController@insertWisata');
Route::put('/wisata/{id}','WisataController@updateWisata');

Route::delete('/wisata/{id}','WisataController@deleteWisata');

Route::get('/email','EmailController@showForm');
Route::post('/email','EmailController@sub');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/api_user','ApiController@showUser');
Route::get('/api_user_guzzle','ApiController@showUserGuzzle');

Route::get('/translate','ApiController@translate');
Route::post('/translate','ApiController@posttranslate');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
	
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('destination', 'DestinationController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('point', 'PointController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('order', 'OrderController',['except' => ['show']]);
});
Route::group(['middleware' => 'auth'],function(){
	Route::resource('tiket', 'TiketController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('blog', 'BlogController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('event', 'EventController',['except' => ['show']]);
});

app/Destination.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Destination extends Model
{
    protected $dates = ['created_at'];
    protected $fillable = [
        'destination_id','destination_name','destination_image','destination_content','destination_author','created_at','trash','destination_category','destination_lat','destination_long','destination_addres','rata_rating','jumlah_response','seo_link'
    ];
    protected $primaryKey = 'destination_id';

    public function islands(){
        return $this->hasOne('App\Island', 'island_id', 'island_id');
    }

    public function DestinationToRating(){
        return $this->hasMany('App\Rating','destination_id','destination_id');
    }

    public function Point(){
        return $this->hasMany('App\Point', 'destination_id');
    }
}

app/Http/Controllers/API/DestinationController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Destination;
use Validator;
use Illuminate\Support\Facades\DB;

class DestinationController extends Controller
{
    public function index(Request $request)
    {          

        $destination = Destination::with('islands')->offset($request->input('offset'))->limit($request->input('limit'))->orderby('created_at','DESC')->get();
        $data = $destination->toArray();

        return response()->json([
            'status' => true,
            'pesan' => 'data destinasi berhasil ditampilkan',
            'data' => $data
        ], 200);
    }

    public function store(Request $request){
        $input = $request->all();

        $validator = Validator::make($input,[
            'destination_name' => 'required',
            'destination_image' => 'required',
            'destination_content' => 'required',
            'destination_author' => 'required'
        ]);
        if ($validator->fails()) {
            $response=[
                'success' => false,
                'data' => 'Validation Error',
                'message' => $validator->errors()
            ];
            return response()->json($response,404);
        }

        $destination = Destination::create($input);
        $data = $destination->toArray();

        $response=[
            'success' => true,
            'date' => $data,
            'message' => 'Data destinasi berhasil di tambahkan'
        ];
        return response()->json($response,200);
    }

    public function populerDestination(Request $request){

        
        $dompet_point = DompetPoint::with('islands')->where('user_id',$request->input('user_id'))->get();
        $data = $dompet_point->toArray();

        $var = $dompet_point;
        $total =0;
        foreach($var as $a){
            $total += $a->point_value;
        }
        return response()->json([
            'status' => true,
            'pesan' => 'data berhasil ditampilkan',
            'data' => $data,
            'total_point' => $total
        ], 200);
    }

    public function newDes(){

        $destination = Destination::with('islands')->orderby('created_at')->offset(0)->limit(5)->get();
        $data = $destination->toArray();

        return response()->json([
            'status' => true,
            'pesan' => 'data destinasi berhasil ditampilkan',
            'data' => $data
        ], 200);        
    }

    public function updatededes(Request $request){
        $destination = Destination::where('destination_id',$request->input('destination_id'));

        $destination->update(['rata_rating'=> $request->input('rata_rating')]);
        $destination->update(['jumlah_response'=> $request->input('jumlah_response')]);
        // $data = $destination->toArray();
        return response()->json([
            'status' => true,
            'pesan' => 'data destinasi berhasil diperbaharui',
            'data' => [$request->all()]
        ], 200);  
    }
}

app/Http/Controllers/DestinationController.php
<?php

namespace App\Http\Controllers;
use App\Destination;

use Illuminate\Http\Request;

class DestinationController extends Controller
{
    public function index(){
        $datades=Destination::get();
        return view('destination.index',compact('datades'));
    }


    public function create()
    {
        return view('destination.create');
    }

    public function store(Request $request){
        $file = $request->file('file');
        $nama_file = time()."_".$file->getClientOriginalName();
        $tujuan_upload = 'data_file';
		$file->move($tujuan_upload,$nama_file);

        $destination=Destination::create([
            'destination_name' => $request->input('destination_name'),        
            'destination_image' => $nama_file,
            'destination_addres' => $request->input('destination_addres'),
            'destination_author' => $request->input('destination_author'),
            'destination_category' => $request->input('destination_category'),
            'destination_lat' => $request->input('destination_lat'),
            'destination_long' => $request->input('destination_long'),
        ]);
            
        return redirect()->route('destination.index')->withStatus(__('Destination sukses dibuat'));
    }

    public function destroy($destination_id){
        $datades= Destination::where('destination_id',$destination_id);
        $datades->delete();
        // return dd($datades);
        return redirect()->route('destination.index')->withStatus(__('Destination sukses dihapus'));
    }

    public function edit($destination_id){
        $datades=Destination::where('destination_id',$destination_id)->get();
        // return $datades;
        return view('destination.edit',compact('datades'));
    }

    public function update(Request $request, $destination_id)
    {
        $datades=Destination::where('destination_id', $destination_id)->first();
        $datades->destination_name = $request->destination_name;
        $datades->destination_addres = $request->destination_addres;
        $datades->destination_category = $request->destination_category;
        $datades->destination_lat = $request->destination_lat;
        $datades->destination_long = $request->destination_long;
        $datades->destination_author = $request->destination_author;

        $datades->save();
        
        return redirect()->route('destination.index');
        // return $destination_id;
    }
}

resources/views/destination/create.blade.php
@extends('layouts.app', ['activePage' => 'destination-management', 'titlePage' => __('Destination Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('destination.store') }}" autocomplete="off" class="form-horizontal" enctype="multipart/form-data">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Add Destination') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('destination.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                  </div>
                </div>

                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Destination Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('destination_name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('destination_name') ? ' is-invalid' : '' }}" name="destination_name" id="input-name" type="text" placeholder="{{ __('Destination Name') }}" value="{{ old('destination_name') }}" required="true" aria-required="true"/>
                      @if ($errors->has('destination_name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>  

                

               
               <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('Destination Address') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('destination_addres') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('destination_addres') ? ' is-invalid' : '' }}" name="destination_addres" id="input-name" type="text" placeholder="{{ __('Destination Address') }}" value="{{ old('destination_addres') }}" required="false" aria-required="true"/>
                    @if ($errors->has('destination_addres'))
                      <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_addres') }}</span>
                    @endif
                  </div>
                </div>                
              </div>   

              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('Destination Category') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('destination_category') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('destination_category') ? ' is-invalid' : '' }}" name="destination_category" id="input-name" type="text" placeholder="{{ __('Destination Categoty') }}" value="{{ old('destination_category') }}" required="false" aria-required="true"/>
                    @if ($errors->has('destination_category'))
                      <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_category') }}</span>
                    @endif
                  </div>
                </div>                
              </div>   

              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('Destination Latitude') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('destination_lat') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('destination_lat') ? ' is-invalid' : '' }}" name="destination_lat" id="input-name" type="text" placeholder="{{ __('Destination Latitude') }}" value="{{ old('destination_lat') }}" required="false" aria-required="true"/>
                    @if ($errors->has('destination_lat'))
                      <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_lat') }}</span>
                    @endif
                  </div>
                </div>                
              </div>   

              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('Destination Longitude') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('destination_long') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('destination_long') ? ' is-invalid' : '' }}" name="destination_long" id="input-name" type="text" placeholder="{{ __('Destination Longitude') }}" value="{{ old('destination_long') }}" required="false" aria-required="true"/>
                    @if ($errors->has('destination_long'))
                      <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_long') }}</span>
                    @endif
                  </div>
                </div>                
              </div>   
              
              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('Destination Author') }}</label>
                <div class="col-sm-7">
                  <div class="form-group{{ $errors->has('destination_author') ? ' has-danger' : '' }}">
                    <input class="form-control{{ $errors->has('destination_author') ? ' is-invalid' : '' }}" name="destination_author" id="input-name" type="text" placeholder="{{ __('Destination Author') }}" value="{{ old('destination_author',auth()->user()->name) }}" required="false" aria-required="true"/>
                    @if ($errors->has('destination_author'))
                      <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_author') }}</span>
                    @endif
                  </div>
                </div>                
              </div>                


              <div class="row">
                <label class="col-sm-2 col-form-label">{{ __('Destination Image') }}</label>
                <div class="col-sm-7">                     
                <div>
                  <input type="file" id="input-file-now" class="dropify" data-default-file="" name="file">          
         
                </div>
                </div>
             </div>              
           
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Add Destination') }}</button>
              </div>
            </div>
          </form>          
        </div>   
      </div>    
        </div>
      </div>
    </div>
  </div>
   
        
@endsection

resources/views/destination/edit.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'titlePage' => __('User Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
                @foreach($datades as $datades)
          <form method="post" action="{{ route('destination.update', $datades->destination_id) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Edit User') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('destination.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                  </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">{{ __('Destination Name') }}</label>
                    <div class="col-sm-7">
                      <div class="form-group{{ $errors->has('destination_name') ? ' has-danger' : '' }}">
                      <input  class="form-control{{ $errors->has('destination_name') ? ' is-invalid' : '' }}" name="destination_name" id="input-name" type="text" placeholder="{{ __('Destination Name') }}" value="{{ $datades->destination_name}}" required="true" aria-required="true"/>
                        @if ($errors->has('destination_name'))
                          <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_name') }}</span>
                        @endif
                      </div>
                    </div>
                  </div>  
  
                 
                 <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Destination Address') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('destination_addres') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('destination_addres') ? ' is-invalid' : '' }}" name="destination_addres" id="input-name" type="text" placeholder="{{ __('Destination Address') }}" value="{{ $datades->destination_addres}}" required="false" aria-required="true"/>
                      @if ($errors->has('destination_addres'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_addres') }}</span>
                      @endif
                    </div>
                  </div>                
                </div>   
  
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Destination Category') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('destination_category') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('destination_category') ? ' is-invalid' : '' }}" name="destination_category" id="input-name" type="text" placeholder="{{ __('Destination Categoty') }}" value="{{ $datades->destination_category}}" required="false" aria-required="true"/>
                      @if ($errors->has('destination_category'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_category') }}</span>
                      @endif
                    </div>
                  </div>                
                </div>   
  
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Destination Latitude') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('destination_lat') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('destination_lat') ? ' is-invalid' : '' }}" name="destination_lat" id="input-name" type="text" placeholder="{{ __('Destination Latitude') }}" value="{{ $datades->destination_lat}}" required="false" aria-required="true"/>
                      @if ($errors->has('destination_lat'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_lat') }}</span>
                      @endif
                    </div>
                  </div>                
                </div>   
  
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Destination Longitude') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('destination_long') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('destination_long') ? ' is-invalid' : '' }}" name="destination_long" id="input-name" type="text" placeholder="{{ __('Destination Longitude') }}" value="{{ $datades->destination_long}}" required="false" aria-required="true"/>
                      @if ($errors->has('destination_long'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_long') }}</span>
                      @endif
                    </div>
                  </div>                
                </div>   
                
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Destination Author') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('destination_author') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('destination_author') ? ' is-invalid' : '' }}" name="destination_author" id="input-name" type="text" placeholder="{{ __('Destination Author') }}" value="{{ old('destination_author',auth()->user()->name) }}" required="false" aria-required="true"/>
                      @if ($errors->has('destination_author'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('destination_author') }}</span>
                      @endif
                    </div>
                  </div>                
                </div>    
               
          
                
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
              </div>
            </div>
            @endforeach
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/destination/index.blade.php
@extends('layouts.app', ['activePage' => 'destination-management', 'titlePage' => __('Destination Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Destination') }}</h4>
                <p class="card-category"> {{ __('Here you can manage destination') }}</p>
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                <div class="row">
                  <div class="col-12 text-right">
                    <a href="{{ route('destination.create') }}" class="btn btn-sm btn-primary">{{ __('Add destinasi') }}</a>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                        <th>
                            {{ __('No') }}
                        </th>
                   
                      <th>
                          {{ __('Nama') }}
                      </th>
                      <th>
                          {{ __('Gambar') }}
                      </th>
                      <th>
                        {{ __('Author') }}
                      </th>  
                      <th>
                        {{ __('Lokasi') }}
                      </th> 
                      <th>
                        {{ __('Created At') }}
                      </th>                     
                      <th class="text-right">
                        {{ __('Actions') }}
                      </th>
                    </thead>
                    <tbody>
                        <?php $no = 0;?>
                      @foreach($datades as $destinasi)
                      <?php $no++ ;?>
                        <tr>
                          <td>
                            {{ $no }}
                          </td>
                         
                          <td>
                            {{ $destinasi->destination_name }}
                          </td>
                          <td>
                              <img width="150px" src="{{ url('/data_file/'.$destinasi->destination_image) }}">
                          </td>
                          <td>
                            {{ $destinasi->destination_author }}
                          </td>
                          <td>
                            {{ $destinasi->destination_lat }} , {{ $destinasi->destination_long }}
                          </td>
                          <td>
                            {{ $destinasi->created_at }}
                          </td>
                          
                          <td class="td-actions text-right">
                           
                             <form action="{{ route('destination.destroy',$destinasi->destination_id) }}" method="post">
                                  @csrf
                                  @method('DELETE')                              
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('destination.edit', $destinasi->destination_id) }}" data-original-title="" title="">
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <button type="button" class="btn btn-danger btn-link" data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">
                                    <i class="material-icons">close</i>
                                    <div class="ripple-container"></div>
                                </button>
                              </form>                         
                              
                           
                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection