routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

//start new root
//home page
Route::get('/','GumiHomeController@index')->name('gumi_home.index');
Route::get('/gumi-home','GumiHomeController@index')->name('gumi_home.index');
Route::get('/gumi-destinations','GumiHomeController@destinations')->name('gumi_destination.destinations');
Route::get('/gumi-blogs','GumiHomeController@blogs')->name('gumi_blog.blogs');
Route::get('/gumi-events','GumiHomeController@events')->name('gumi_event.events');
Route::get('/gumi-destination-detail/{seo_link}','GumiHomeController@destination_detail')->name('gumi_destination.detail');
Route::get('/gumi-blog-detail/{seo_link}','GumiHomeController@blog_detail')->name('gumi_blog.detail');
Route::get('/gumi-event-detail/{seo_link}','GumiHomeController@event_detail')->name('gumi_event.detail');
//end migrasi route

Route::get('/tentang-gumi-lombok', function () {
    return view('welcome');
})->name('gumi');




Route::get('/old_home', 'DepanController@index')->name('depan.index');
// Route::put('/detail-blog/{blog_id}','DepanController@detailBlog');
Route::get('/detail-blog/{blog_id}', 'DepanController@detailBlog')->name('depan.blog_detail');
Route::get('/detail-destinasi/{destination_id}','DepanController@detailDestinasi')->name('depan.destinasi_detail');
Route::get('/informasi-category/{blog_category}','DepanController@category')->name('depan.blog_category');
Route::get('/informasi-destinasi-wisata','DepanController@allDestinasi')->name('depan.semu_destinasi');

Route::get('/maps','DepanController@maps')->name('depan.maps');


// Route::resource('/order', 'OrderController');

Route::get('wisata','WisataController@index')->middleware('api');
Route::post('wisata','WisataController@insertWisata');
Route::put('/wisata/{id}','WisataController@updateWisata');

Route::delete('/wisata/{id}','WisataController@deleteWisata');

Route::get('/email','EmailController@showForm');
Route::post('/email','EmailController@sub');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/api_user','ApiController@showUser');
Route::get('/api_user_guzzle','ApiController@showUserGuzzle');

Route::get('/translate','ApiController@translate');
Route::post('/translate','ApiController@posttranslate');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
	
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('destination', 'DestinationController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('point', 'PointController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('order', 'OrderController',['except' => ['show']]);
});
Route::group(['middleware' => 'auth'],function(){
	Route::resource('tiket', 'TiketController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('blog', 'BlogController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('event', 'EventController',['except' => ['show']]);
});

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="white" data-image="{{ asset('material') }}/img/sidebar-1.jpg">
  <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
  <div class="logo">
    <a href="gumilombok.id/" class="simple-text logo-normal">
      {{ __('Gumi Lombok') }}
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      
     
      <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('home') }}">
          <i class="material-icons">dashboard</i>
            <p>{{ __('Dashboard') }}</p>
        </a>
      </li>
      <li class="nav-item {{ ($activePage == 'profile' || $activePage == 'user-management') ? ' active' : '' }}">
        <a class="nav-link" data-toggle="collapse" href="#laravelExample" aria-expanded="true">
          <i><img style="width:25px" src="{{ asset('material') }}/img/laravel.svg"></i>
          <p>{{ __('Management') }}
            <b class="caret"></b>
          </p>
        </a>
        <div class="collapse show" id="laravelExample">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'profile' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('profile.edit') }}">
                <span class="sidebar-mini"> UP </span>
                <span class="sidebar-normal">{{ __('User profile') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'user-management' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('user.index') }}">
                <span class="sidebar-mini"> UM </span>
                <span class="sidebar-normal"> {{ __('User Management') }} </span>
              </a>
            </li>
            {{-- destination --}}
            <li class="nav-item{{ $activePage == 'destination-management' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('destination.index') }}">
                <span class="sidebar-mini"> DM </span>
                <span class="sidebar-normal"> {{ __('Destination Management') }} </span>
              </a>
            </li>
            {{-- Point --}}
            <li class="nav-item{{ $activePage == 'point-management' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('point.index') }}">
                  <span class="sidebar-mini"> PM </span>
                  <span class="sidebar-normal"> {{ __('Point Management') }} </span>
                </a>
            </li>
            {{-- Order --}}
            <li class="nav-item{{ $activePage == 'order-management' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('order.index') }}">
                <span class="sidebar-mini"> OM </span>
                <span class="sidebar-normal"> {{ __('Order Management') }} </span>
              </a>
          </li>
          {{-- Tiket --}}
          <li class="nav-item{{ $activePage == 'tiket-management' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('tiket.index') }}">
                <span class="sidebar-mini"> TM </span>
                <span class="sidebar-normal"> {{ __('tiket Management') }} </span>
              </a>
          </li>
          {{-- Blog --}}
          <li class="nav-item{{ $activePage == 'blog-management' ? ' active' : '' }}">
            <a class="nav-link" href="{{ route('blog.index') }}">
              <span class="sidebar-mini"> TM </span>
              <span class="sidebar-normal"> {{ __('Blogs Management') }} </span>
            </a>
           </li>
           {{-- Event --}}
          <li class="nav-item{{ $activePage == 'event_management' ? ' active' : '' }}">
            <a class="nav-link" href="{{ route('event.index') }}">
              <span class="sidebar-mini"> TM </span>
              <span class="sidebar-normal"> {{ __('Event Management') }} </span>
            </a>
           </li>
          </ul>
        </div>
      </li>
      {{-- <li class="nav-item{{ $activePage == 'table' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('table') }}">
          <i class="material-icons">content_paste</i>
            <p>{{ __('Table List') }}</p>
        </a>
      </li>
      <li class="nav-item{{ $activePage == 'typography' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('typography') }}">
          <i class="material-icons">library_books</i>
            <p>{{ __('Typography') }}</p>
        </a>
      </li>
      <li class="nav-item{{ $activePage == 'icons' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('icons') }}">
          <i class="material-icons">bubble_chart</i>
          <p>{{ __('Icons') }}</p>
        </a>
      </li>
      <li class="nav-item{{ $activePage == 'map' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('map') }}">
          <i class="material-icons">location_ons</i>
            <p>{{ __('Maps') }}</p>
        </a>
      </li>
      <li class="nav-item{{ $activePage == 'notifications' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('notifications') }}">
          <i class="material-icons">notifications</i>
          <p>{{ __('Notifications') }}</p>
        </a>
      </li>
      <li class="nav-item{{ $activePage == 'language' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('language') }}">
          <i class="material-icons">language</i>
          <p>{{ __('RTL Support') }}</p>
        </a>
      </li>
      <li class="nav-item active-pro{{ $activePage == 'upgrade' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('upgrade') }}">
          <i class="material-icons">unarchive</i>
          <p>{{ __('Upgrade to PRO') }}</p>
        </a>
      </li> --}}
    </ul>
  </div>
</div>

resources/views/layouts/navbars/sidebar2.blade.php
<div class="sidebar" data-color="orange" data-background-color="white" data-image="{{ asset('material') }}/img/sidebar-1.jpg">
    <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"
  
        Tip 2: you can also add an image using data-image tag
    -->
    <div class="logo">
      <a href="gumilombok.id/" class="simple-text logo-normal">
        {{ __('Gumi Lombok') }}
      </a>
    </div>
    <div class="sidebar-wrapper">
      <ul class="nav">
        
       
        <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
          <a class="nav-link" href="{{ route('home') }}">
            <i class="material-icons">dashboard</i>
              <p>{{ __('Dashboard') }}</p>
          </a>
        </li>
        <li class="nav-item {{ ($activePage == 'profile' || $activePage == 'user-management') ? ' active' : '' }}">
          <a class="nav-link" data-toggle="collapse" href="#laravelExample" aria-expanded="true">
            <i><img style="width:25px" src="{{ asset('material') }}/img/laravel.svg"></i>
            <p>{{ __('Management') }}
              <b class="caret"></b>
            </p>
          </a>
          <div class="collapse show" id="laravelExample">
            <ul class="nav">
              <li class="nav-item{{ $activePage == 'profile' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('profile.edit') }}">
                  <span class="sidebar-mini"> UP </span>
                  <span class="sidebar-normal">{{ __('User profile') }} </span>
                </a>
              </li>
             
             
              
              
            
            
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>