routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

//start new root
//home page
Route::get('/','GumiHomeController@index')->name('gumi_home.index');
Route::get('/gumi-home','GumiHomeController@index')->name('gumi_home.index');
Route::get('/gumi-destinations','GumiHomeController@destinations')->name('gumi_destination.destinations');
Route::get('/gumi-blogs','GumiHomeController@blogs')->name('gumi_blog.blogs');
Route::get('/gumi-events','GumiHomeController@events')->name('gumi_event.events');
Route::get('/gumi-destination-detail/{seo_link}','GumiHomeController@destination_detail')->name('gumi_destination.detail');
Route::get('/gumi-blog-detail/{seo_link}','GumiHomeController@blog_detail')->name('gumi_blog.detail');
Route::get('/gumi-event-detail/{seo_link}','GumiHomeController@event_detail')->name('gumi_event.detail');
//end migrasi route

Route::get('/tentang-gumi-lombok', function () {
    return view('welcome');
})->name('gumi');




Route::get('/old_home', 'DepanController@index')->name('depan.index');
// Route::put('/detail-blog/{blog_id}','DepanController@detailBlog');
Route::get('/detail-blog/{blog_id}', 'DepanController@detailBlog')->name('depan.blog_detail');
Route::get('/detail-destinasi/{destination_id}','DepanController@detailDestinasi')->name('depan.destinasi_detail');
Route::get('/informasi-category/{blog_category}','DepanController@category')->name('depan.blog_category');
Route::get('/informasi-destinasi-wisata','DepanController@allDestinasi')->name('depan.semu_destinasi');

Route::get('/maps','DepanController@maps')->name('depan.maps');


// Route::resource('/order', 'OrderController');

Route::get('wisata','WisataController@index')->middleware('api');
Route::post('wisata','WisataController@insertWisata');
Route::put('/wisata/{id}','WisataController@updateWisata');

Route::delete('/wisata/{id}','WisataController@deleteWisata');

Route::get('/email','EmailController@showForm');
Route::post('/email','EmailController@sub');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/api_user','ApiController@showUser');
Route::get('/api_user_guzzle','ApiController@showUserGuzzle');

Route::get('/translate','ApiController@translate');
Route::post('/translate','ApiController@posttranslate');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
	
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('destination', 'DestinationController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('point', 'PointController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('order', 'OrderController',['except' => ['show']]);
});
Route::group(['middleware' => 'auth'],function(){
	Route::resource('tiket', 'TiketController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('blog', 'BlogController',['except' => ['show']]);
});

Route::group(['middleware' => 'auth'],function(){
	Route::resource('event', 'EventController',['except' => ['show']]);
});

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $evnt=['created_at'];
    protected $fillable = [
        'event_id','event_name','event_image','event_cost','event_location','event_date','created_at','updated_at','trash'
    ];
    protected $primaryKey ='event_id';
}

app/Http/Controllers/API/EventController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Event;

class EventController extends Controller
{
    public function index(Request $request){
        $event=Event::offset($request->input('offset'))->limit($request->input('limit'))->orderby('created_at','DESC')->get();
        $data = $event->toArray();

        return response()->json([
            'status' => true,
            'pesan' => 'data event tampil',
            'data' => $data
        ],200);
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Event;

class EventController extends Controller
{
    public function index()
    {
        $dataevent=Event::get();
        return view('event.index',compact('dataevent'));
    }
}

resources/views/event/index.blade.php
@extends('layouts.app', ['activePage' => 'event-management', 'titlePage' => __('Event Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Event') }}</h4>
                <p class="card-category"> {{ __('Here you can manage blog post') }}</p>
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                <div class="row">
                  <div class="col-12 text-right">
                    <a href="{{ route('blog.create') }}" class="btn btn-sm btn-primary">{{ __('Add New Post') }}</a>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                        <th>
                            {{ __('No') }}
                        </th>
                   
                      <th>
                          {{ __('Judul event') }}
                      </th>                      
                      <th>
                        {{ __('Gambar') }}
                      </th>  
                      <th>
                        {{ __('Event Cost') }}
                      </th>
                      <th>
                        {{ __('Event Date') }}
                      </th> 
                      <th>
                        {{ __('Created At') }}
                      </th>                     
                      <th class="text-right">
                        {{ __('Actions') }}
                      </th>
                    </thead>
                    <tbody>
                        <?php $no = 0;?>
                      @foreach($dataevent as $event)
                      <?php $no++ ;?>
                        <tr>
                          <td>
                            {{ $no }}
                          </td>
                         
                          <td>
                            {{ $event->event_name }}
                          </td>
                          
                          <td>
                              <img width="150px" src="{{ url('/data_file/event/'.$event->event_image) }}">
                          </td>
                          <td>
                            {{ $event->event_cost }}
                          </td>
                          <td>
                            {{ $event->event_date }}
                          </td>
                          <td>
                            {{ $event->created_at }}
                          </td>
                         
                          
                          {{-- <td class="td-actions text-right">
                           
                             <form action="{{ route('blog.destroy',$blog->blog_id) }}" method="post">
                                  @csrf
                                  @method('DELETE')                              
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('blog.edit', $blog->blog_id) }}" data-original-title="" title="">
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <button type="button" class="btn btn-danger btn-link" data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">
                                    <i class="material-icons">close</i>
                                    <div class="ripple-container"></div>
                                </button>
                              </form>                         
                              
                           
                          </td> --}}
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection